import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { api, ApiError } from "@/lib/http";

export const runtime = "nodejs";
type Context = { params: Promise<{ id: string }> };

export async function GET(_request: NextRequest, context: Context) {
  const { id } = await context.params;
  // IDs are generated by the server. Do not accept paths, filenames or remote image URLs.
  if (!/^[a-z0-9]{20,40}$/.test(id)) return NextResponse.json({ error: "Фотография не найдена." }, { status: 404 });
  const photo = await db.teamPhoto.findUnique({ where: { id }, select: { data: true } });
  if (!photo) return NextResponse.json({ error: "Фотография не найдена." }, { status: 404 });
  return new Response(new Uint8Array(photo.data), {
    headers: {
      "Content-Type": "image/webp",
      "Content-Length": String(photo.data.byteLength),
      "Cache-Control": "public, max-age=0, must-revalidate",
      "X-Content-Type-Options": "nosniff",
      "Content-Security-Policy": "default-src 'none'",
    },
  });
}

export async function DELETE(request: NextRequest, context: Context) {
  return api(async () => {
    const user = await requireUser("TEAM");
    const id = (await context.params).id;
    const photo = await db.teamPhoto.findUnique({ where: { id }, select: { team: { select: { ownerId: true } } } });
    if (!photo) throw new ApiError(404, "Фотография не найдена.");
    if (photo.team.ownerId !== user.id) throw new ApiError(403, "Вы можете удалять только фотографии своей команды.");
    await db.teamPhoto.deleteMany({ where: { id, team: { ownerId: user.id } } });
    return { deleted: true };
  }, request);
}
