import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

test('business to team: clarify, improve, publish, propose, accept and confirm', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const title = 'Учёт оплат — проверка полного сценария'
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'С чего начнём?' })).toBeVisible()
  await page.screenshot({ path: 'test-results/home.png', fullPage: true })
  await page.getByRole('button', { name: 'Перейти в кабинет' }).click()
  await page.getByRole('link', { name: 'Создать задачу', exact: true }).last().click()
  await page.getByLabel('Что вы хотите изменить?').fill('Мы небольшой учебный центр. Сейчас отмечаем оплату курсов вручную и иногда теряем сведения. Хотим навести порядок с оплатами.')
  await page.getByRole('button', { name: 'Уточнить с помощником' }).click()
  await expect(page.getByText('Локальный резервный режим', { exact: true })).toBeVisible()
  await expect(page.locator('.question')).toHaveCount(5)
  await page.locator('#q_title').fill(title)
  await page.locator('#q_users').fill('Пока не знаю')
  await page.locator('#q_data').fill('Пока не знаю')
  await page.locator('#q_expected_result').fill('Пока не знаю')
  await page.getByRole('button', { name: 'Сформировать карточку' }).click()
  await expect(page.locator('#card-title')).toHaveValue(title)
  await expect(page.locator('#card-data')).toHaveValue('')
  await page.getByRole('button', { name: 'К подтверждению' }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Подтвердить сведения', exact: true }).click()
  await expect(page.getByText('Изменение рейтинга: +20 баллов. Официально: 20 / 100.')).toBeVisible()
  await page.getByRole('button', { name: 'Вернуться к карточке' }).click()
  const fixtures = JSON.parse(fs.readFileSync(path.resolve('../seed/cards.json'), 'utf8'))
  const card = fixtures[0].card
  for (const [key, value] of Object.entries(card)) {
    if (key !== 'title' && key !== 'success_criteria') await page.locator(`#card-${key}`).fill(value as string)
  }
  await page.getByRole('button', { name: 'Добавить критерий' }).click()
  await page.locator('#criterion-0-criterion').fill(card.success_criteria[0].criterion)
  await page.locator('#criterion-0-expected_value').fill(card.success_criteria[0].expected_value)
  await page.locator('#criterion-0-verification_method').fill(card.success_criteria[0].verification_method)
  await page.getByRole('button', { name: 'К подтверждению' }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Подтвердить сведения', exact: true }).click()
  await expect(page.getByText('Изменение рейтинга: +80 баллов. Официально: 100 / 100.')).toBeVisible()
  await page.getByRole('button', { name: 'Опубликовать в каталоге' }).click()
  await page.getByRole('button', { name: 'Открыть опубликованную задачу' }).click()
  const taskUrl = page.url()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  await page.getByRole('link', { name: 'Все задачи', exact: true }).click()
  await expect(page.getByRole('heading', { name: title })).toBeVisible()
  await page.screenshot({ path: 'test-results/catalog.png', fullPage: true })
  await page.getByRole('button', { name: 'Сменить профиль' }).click()
  await page.getByRole('button', { name: 'Я студенческая команда' }).click()
  await page.getByRole('button', { name: 'Перейти в кабинет' }).click()
  await page.goto(taskUrl)
  await page.getByLabel('Идея решения').fill('Реестр с импортом CSV и поиском по курсу')
  await page.getByLabel('План работы').fill('Интервью, прототип, импорт, сверка результатов')
  await page.getByLabel('Предполагаемый срок').fill('3 недели')
  await page.getByLabel('Ссылка на прототип').fill('https://example.org/taskup-demo/e2e')
  await page.getByRole('button', { name: 'Отправить предложение' }).click()
  await expect(page.getByText('Предложение отправлено. Бизнес рассмотрит его вручную.')).toBeVisible()
  await page.getByRole('button', { name: 'Сменить профиль' }).click()
  await page.getByRole('button', { name: 'Перейти в кабинет' }).click()
  const row = page.getByRole('row').filter({ hasText: title })
  await row.getByRole('link', { name: '1 предложений' }).click()
  await page.getByRole('button', { name: 'Выбрать команду' }).click()
  await expect(page.getByText('Команда выбрана', { exact: true })).toBeVisible()
  const proposalsUrl = page.url()
  await page.getByRole('button', { name: 'Сменить профиль' }).click()
  await page.getByRole('button', { name: 'Я студенческая команда' }).click()
  await page.getByRole('button', { name: 'Перейти в кабинет' }).click()
  const proposal = page.locator('section.panel').filter({ has: page.getByRole('link', { name: title }) })
  await proposal.getByLabel('Что сделано').fill('Прототип реестра готов. Импортировали 100 строк и сверили контрольные суммы.')
  await proposal.getByRole('button', { name: 'Отправить результат' }).click()
  await expect(proposal.getByText('На проверке · 0 баллов')).toBeVisible()
  await page.getByRole('button', { name: 'Сменить профиль' }).click()
  await page.getByRole('button', { name: 'Перейти в кабинет' }).click()
  await page.goto(proposalsUrl)
  await page.getByRole('button', { name: 'Подтвердить результат' }).click()
  await expect(page.getByText('Результат подтверждён · +10 баллов команде')).toBeVisible()
  await page.screenshot({ path: 'test-results/result.png', fullPage: true })
  await page.getByRole('button', { name: 'Сменить профиль' }).click()
  await page.getByRole('button', { name: 'Я студенческая команда' }).click()
  await page.getByRole('button', { name: 'Перейти в кабинет' }).click()
  await expect(page.locator('.accent-stat strong')).toHaveText('10 баллов')
  expect(errors).toEqual([])
})

test('public low score is visible, filters clear, and form survives API failure', async ({ page }) => {
  await page.goto('/catalog')
  await page.getByRole('combobox', { name: 'Готовность', exact: true }).selectOption('Черновик')
  await expect(page.getByRole('heading', { name: 'Быстрая инвентаризация магазина' })).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить' }).click()
  await expect(page.getByRole('heading', { name: 'Порядок в оплатах учебного центра' })).toBeVisible()
  await page.goto('/')
  await page.getByRole('button', { name: 'Я студенческая команда' }).click()
  await page.getByRole('button', { name: 'Перейти в кабинет' }).click()
  await page.goto('/tasks/4')
  await page.getByLabel('Идея решения').fill('Проверка сохранения текста при ошибке')
  await page.getByLabel('План работы').fill('Ввести данные и проверить повторную отправку')
  await page.getByLabel('Предполагаемый срок').fill('2 недели')
  await page.route('**/api/tasks/4/proposals', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: { code: 'test_error', message: 'Тестовая ошибка сервера', details: {} } }) }))
  await page.getByRole('button', { name: 'Отправить предложение' }).click()
  await expect(page.getByRole('alert')).toContainText('Тестовая ошибка сервера')
  await expect(page.getByLabel('Идея решения')).toHaveValue('Проверка сохранения текста при ошибке')
  await expect(page.getByRole('button', { name: 'Отправить предложение' })).toBeEnabled()
})
