import { useState } from 'react'
import { ArrowLeft, ArrowRight, Check, Clock3, FileCheck2, Plus, Send, Trophy, X } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useActor } from '../App'
import { api } from '../api/client'
import { useAction, useResource } from '../api/hooks'
import { Empty, Loading, Notice, PageHeading, SafeLink, ScoreBadge } from '../components/common'
import type { Milestone, PrivateTask, Proposal } from '../types'

const STATUS = { pending: 'На рассмотрении', accepted: 'Команда выбрана', rejected: 'Отклонено' }
export function BusinessDashboard() {
  const { actor } = useActor()
  const resource = useResource<PrivateTask[]>('/business/tasks')
  const tasks = resource.data || []
  const published = tasks.filter(t => t.is_published)
  return <><PageHeading eyebrow={actor?.name} title="Мои задачи" description="Добавляйте ясность в задачи и выбирайте команды, с которыми хотите работать." action={<Link to="/business/tasks/new" className="button"><Plus size={17} />Создать задачу</Link>} />
    <div className="stats"><div><span>Всего задач</span><strong>{tasks.length}</strong><FileCheck2 size={23} /></div><div><span>В общем каталоге</span><strong>{published.length}</strong><Check size={23} /></div><div><span>Предложений команд</span><strong>{tasks.reduce((sum, t) => sum + t.proposal_count, 0)}</strong><Send size={23} /></div></div>
    <Notice error={resource.error} />{resource.error && <button className="button secondary" onClick={resource.reload}>Повторить загрузку</button>}{resource.loading ? <Loading /> : !tasks.length ? <Empty title="Первая задача начинается с описания" text="Расскажите о потребности бизнеса. Помощник задаст уточняющие вопросы."><Link className="button" to="/business/tasks/new">Создать задачу</Link></Empty> : <section className="panel table-panel"><div className="table-title"><h2>Задачи вашей организации</h2><span className="small muted">Рейтинг последней подтверждённой версии</span></div><div className="table-scroll"><table><thead><tr><th>Задача</th><th>Готовность</th><th>Публикация</th><th>Отклики</th><th><span className="sr-only">Действия</span></th></tr></thead><tbody>{tasks.map(t => <tr key={t.id}><td><Link className="table-link" to={`/business/tasks/${t.id}/edit`}>{t.draft_card.title || 'Новая задача без названия'}</Link><span className="table-sub">{t.industry}{t.has_unconfirmed_changes ? ' · есть неподтверждённые изменения' : ''}</span></td><td><ScoreBadge score={t.score} /></td><td><span className={`publication ${t.is_published ? 'published' : ''}`}>{t.is_published ? 'В каталоге' : 'Не опубликована'}</span></td><td><Link className="text-link" to={`/business/tasks/${t.id}/proposals`}>{t.proposal_count} предложений</Link></td><td><Link className="icon-button" aria-label={`Редактировать ${t.draft_card.title || 'задачу'}`} to={`/business/tasks/${t.id}/edit`}><ArrowRight size={18} /></Link></td></tr>)}</tbody></table></div></section>}</>
}

function ProposalContent({ proposal }: { proposal: Proposal }) {
  return <><div className="proposal-heading"><div><h3>{proposal.team_name}</h3><div className="tag-row">{[...proposal.team_skills, ...proposal.team_technologies].map(t => <span key={t} className="tag">{t}</span>)}</div></div><span className={`proposal-status ${proposal.status}`}>{STATUS[proposal.status]}</span></div><dl className="proposal-fields"><div><dt>Идея решения</dt><dd>{proposal.idea}</dd></div><div><dt>План работы</dt><dd>{proposal.plan}</dd></div><div><dt>Предполагаемый срок</dt><dd>{proposal.estimated_duration}</dd></div><div><dt>Прототип</dt><dd><SafeLink url={proposal.prototype_url} /></dd></div></dl></>
}
export function ProposalReview() {
  const { id } = useParams()
  const resource = useResource<Proposal[]>(`/business/tasks/${id}/proposals`)
  const action = useAction()
  const proposals = resource.data || []
  function replace(value: Proposal) { resource.setData(current => current?.map(p => p.id === value.id ? value : p) || []) }
  async function decide(proposal: Proposal, status: 'accepted' | 'rejected') {
    replace(await api<Proposal>(`/proposals/${proposal.id}/status`, 'PATCH', { status }))
  }
  return <><Link className="back-link" to="/business"><ArrowLeft size={15} />Мои задачи</Link><PageHeading eyebrow="Решение за бизнесом" title="Предложения команд" description={proposals[0]?.task_title || 'Сравните идею, план и срок. Выберите одну, несколько или ни одной команды.'} /><div className="notice info">Каждое решение независимо. Выбор одной команды оставляет остальные предложения на рассмотрении.</div><Notice error={action.error || resource.error} success={action.success} />{resource.error && <button className="button secondary" onClick={resource.reload}>Повторить загрузку</button>}{resource.loading ? <Loading /> : !proposals.length ? <Empty title="Предложений пока нет" text="После публикации команды смогут предложить свой подход." /> : <div className="proposals-grid">{proposals.map(proposal => <section className="panel" key={proposal.id}><ProposalContent proposal={proposal} /><div className="actions"><button className="button" disabled={action.busy || proposal.status === 'accepted' || !!proposal.milestones.length} onClick={() => action.run(() => decide(proposal, 'accepted'), 'Команда выбрана. Решения по другим предложениям не изменены.')}><Check size={16} />Выбрать команду</button><button className="button secondary" disabled={action.busy || proposal.status === 'rejected' || !!proposal.milestones.length} onClick={() => action.run(() => decide(proposal, 'rejected'), 'Предложение отклонено.')}><X size={16} />Отклонить</button></div>{proposal.milestones.map(m => <div className="milestone" key={m.id}><div className="eyebrow">Демонстрационный этап · Прототип</div><p className="pre-wrap">{m.result_description}</p><SafeLink url={m.result_url} />{m.status === 'confirmed' ? <div className="notice success"><Check size={17} />Результат подтверждён · +{m.points_awarded} баллов команде</div> : <><p className="small muted">Проверьте результат по согласованным критериям, затем подтвердите выполнение.</p><button className="button" disabled={action.busy} onClick={() => action.run(async () => { const value = await api<Milestone>(`/milestones/${m.id}/confirm`, 'POST'); replace({ ...proposal, milestones: [value] }) }, 'Результат подтверждён. Команде начислено 10 баллов.')}><FileCheck2 size={16} />Подтвердить результат</button></>}</div>)}</section>)}</div>}</>
}

export function TeamDashboard() {
  const { actor } = useActor()
  const resource = useResource<{ proposals: Proposal[]; total_points: number }>('/team/proposals')
  const proposals = resource.data?.proposals || []
  return <><PageHeading eyebrow={actor?.name} title="Мои предложения" description="Следите за решениями бизнеса и показывайте результаты выбранных проектов." action={<Link to="/catalog" className="button">Найти задачу<ArrowRight size={17} /></Link>} /><div className="stats"><div><span>Предложений отправлено</span><strong>{proposals.length}</strong><Send size={23} /></div><div><span>Команда выбрана</span><strong>{proposals.filter(p => p.status === 'accepted').length}</strong><Check size={23} /></div><div className="accent-stat"><span>За подтверждённые результаты</span><strong>{resource.data?.total_points || 0}<small> баллов</small></strong><Trophy size={23} /></div></div><p className="small muted">+10 за подтверждённый бизнесом прототип. Отклик и выбор команды баллов не приносят.</p><Notice error={resource.error} />{resource.error && <button className="button secondary" onClick={resource.reload}>Повторить загрузку</button>}{resource.loading ? <Loading /> : !proposals.length ? <Empty title="Ваш следующий проект — в каталоге" text="Выберите интересную задачу и предложите решение."><Link className="button" to="/catalog">Посмотреть задачи</Link></Empty> : <div className="stack">{proposals.map(p => <section className="panel" key={p.id}><Link className="task-title-link" to={`/tasks/${p.task_id}`}>{p.task_title}<ArrowRight size={18} /></Link><ProposalContent proposal={p} />{p.status === 'accepted' && <MilestoneForm proposal={p} onSaved={value => resource.setData(current => current ? { ...current, proposals: current.proposals.map(proposal => proposal.id === p.id ? { ...proposal, milestones: [value] } : proposal) } : current)} />}</section>)}</div>}</>
}
function MilestoneForm({ proposal, onSaved }: { proposal: Proposal; onSaved: (value: Milestone) => void }) {
  const [description, setDescription] = useState('')
  const [url, setUrl] = useState('')
  const action = useAction()
  const milestone = proposal.milestones[0]
  if (milestone) return <div className="milestone"><div className="row-between"><h3>Прототип</h3><span className="tag">{milestone.status === 'confirmed' ? `Подтверждён · +${milestone.points_awarded} баллов` : 'На проверке · 0 баллов'}</span></div><p className="pre-wrap">{milestone.result_description}</p><SafeLink url={milestone.result_url} /><p className="small muted">{milestone.status === 'confirmed' ? 'Бизнес подтвердил выполнение этапа.' : 'Ожидаем подтверждения бизнеса. Баллы пока не начислены.'}</p></div>
  return <form className="milestone" onSubmit={e => { e.preventDefault(); void action.run(async () => { const value = await api<Milestone>(`/proposals/${proposal.id}/milestones`, 'POST', { stage_code: 'prototype', result_description: description, result_url: url || null }); onSaved(value) }, 'Результат отправлен на проверку.') }}><h3><Clock3 size={17} /> Покажите первый результат</h3><p className="small muted">Один демонстрационный этап: прототип. Опишите фактически выполненную работу.</p><Notice error={action.error} success={action.success} /><fieldset disabled={action.busy}><label htmlFor={`result-${proposal.id}`}>Что сделано<textarea id={`result-${proposal.id}`} required minLength={10} maxLength={5000} value={description} onChange={e => setDescription(e.target.value)} /></label><label htmlFor={`result-url-${proposal.id}`}>Ссылка на результат · необязательно<input id={`result-url-${proposal.id}`} type="url" pattern="https?://.*" maxLength={2000} value={url} onChange={e => setUrl(e.target.value)} placeholder="https://" /></label><button className="button" type="submit"><Send size={16} />{action.busy ? 'Отправляем…' : 'Отправить результат'}</button></fieldset></form>
}
